language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - python setup.py test
  - py.test --cov=./

after_success:
  - codecov
