language: python

dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - python setup.py test
  - py.test --cov=./

after_success:
  - codecov
