language: python

dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - python setup.py test
  - py.test --cov=./

after_success:
  - codecov
